version: '3.5'
services:
  hexoids-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - service-network
  hexoids-kafka:
    image: 'wurstmeister/kafka:2.13-2.7.0'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: hexoids-kafka
      KAFKA_ZOOKEEPER_CONNECT: hexoids-zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - hexoids-zookeeper
    networks:
      - service-network

  hexoids-kafka-topic-create:
    build:
      context: src/main/docker/topics/
      dockerfile: Dockerfile
    image: me.pcasaes/hexoids-topics
    environment:
      BROKERS_LIST: hexoids-kafka:9092
    depends_on:
      - hexoids-kafka
    networks:
      - service-network


networks:
  service-network:
    name: hexoids-network