version: '3.5'
services:
  hexoids-kafka:
    image: 'confluentinc/cp-kafka:7.0.1-3-ubi8'
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://hexoids-kafka:29092,PLAINTEXT_HOST://hexoids-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@hexoids-kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://hexoids-kafka:29092,CONTROLLER://hexoids-kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
    networks:
      - service-network

  hexoids-kafka-topic-create:
    build:
      context: src/main/docker/topics/
      dockerfile: Dockerfile
    image: me.pcasaes/hexoids-topics
    environment:
      BROKERS_LIST: hexoids-kafka:9092
    depends_on:
      - hexoids-kafka
    networks:
      - service-network


networks:
  service-network:
    name: hexoids-network