version: '3.5'
services:

  bbop-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - service-network

  bbop-kafka:
    image: 'wurstmeister/kafka:2.12-2.2.1'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: bbop-kafka
      KAFKA_ZOOKEEPER_CONNECT: bbop-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - bbop-zookeeper
    networks:
      - service-network

  bbop-nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - service-network

  bbop-mmo-arcade:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/bbop-mmo-arcade
    environment:
      - VIRTUAL_HOST=${BBOP_HOST}
      - VIRTUAL_PORT=8080
      - JAVA_EXTRA_OPTS=-Dbbop.config.service.kafka.subscriber=false
    depends_on:
      - bbop-kafka
    networks:
      - service-network

  bbop-mmo-arcade-subscriber:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/bbop-mmo-arcade
    environment:
      - JAVA_EXTRA_OPTS=-Dbbop.config.service.kafka.subscriber=true -Dbbop.config.service.client.broadcast.enabled=false
    depends_on:
      - bbop-kafka
    networks:
      - service-network

networks:
  service-network:
    name: bbop-mmo-arcade-network