version: '3.5'
services:
  hexoids-zookeeper:
    image: confluentinc/cp-zookeeper:5.4.4-1-ubi8
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - service-network
  hexoids-kafka:
    image: 'confluentinc/cp-kafka:6.1.1-2-ubi8'
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: hexoids-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://hexoids-kafka:29092,PLAINTEXT_HOST://hexoids-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - hexoids-zookeeper
    networks:
      - service-network

  hexoids-kafka-topic-create:
    build:
      context: src/main/docker/topics/
      dockerfile: Dockerfile
    image: me.pcasaes/hexoids-topics
    environment:
      BROKERS_LIST: hexoids-kafka:9092
    depends_on:
      - hexoids-kafka
    networks:
      - service-network


networks:
  service-network:
    name: hexoids-network