version: '3.5'
services:

  hexoids-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - service-network

  hexoids-kafka:
    image: 'wurstmeister/kafka:2.12-2.5.0'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: hexoids-kafka
      KAFKA_ZOOKEEPER_CONNECT: hexoids-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - hexoids-zookeeper
    networks:
      - service-network


  hexoids:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/hexoids
    environment:
      - JAVA_EXTRA_OPTS=${JAVA_EXTRA_OPTS}
    depends_on:
      - hexoids-kafka
    ports:
      - "28080:8080"
    networks:
      - service-network


networks:
  service-network:
    name: hexoids-network
