version: '3.5'
services:

  hexoids-kafka:
    build:
      context: src/main/docker/kafka
    image: me.pcasaes/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: hexoids-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://hexoids-kafka:29092,PLAINTEXT_HOST://hexoids-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PPLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: -javaagent:/var/lib/kafka/jmx_prometheus_javaagent.jar=9080:/var/lib/kafka/prometheus-config.yml
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@hexoids-kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://hexoids-kafka:29092,CONTROLLER://hexoids-kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
    networks:
      - service-network

  hexoids-nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - service-network
  hexoids-kafka-topic-create:
    build:
      context: src/main/docker/topics/
      dockerfile: Dockerfile
    image: me.pcasaes/hexoids-topics
    environment:
      BROKERS_LIST: hexoids-kafka:9092
    depends_on:
      - hexoids-kafka
    networks:
      - service-network

  hexoids:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/hexoids
    environment:
      - VIRTUAL_HOST=${HEXOIDS_HOST}
      - VIRTUAL_PORT=8080
      - JAVA_EXTRA_OPTS=${JAVA_EXTRA_OPTS} -Dhexoids.config.service.kafka.subscriber=false -Dmp.messaging.incomming.bolt-life-cycle.topic=HEXOIDS_NONE -Dmp.messaging.incommingscore-board-control.topic=HEXOIDS_NONE
    depends_on:
      - hexoids-kafka
      - hexoids-kafka-topic-create
    networks:
      - service-network

  hexoids-subscriber:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/hexoids
    environment:
      - JAVA_EXTRA_OPTS=${JAVA_EXTRA_OPTS} -Dhexoids.config.service.kafka.subscriber=true -Dhexoids.config.service.client-broadcast.enabled=false
    depends_on:
      - hexoids-kafka
    networks:
      - service-network

  hexoids-prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - service-network

  hexoids-grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    volumes:
      - ./src/main/monitoring/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - service-network

networks:
  service-network:
    name: hexoids-network
