version: '3.5'
services:

  hexoids-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - service-network

  hexoids-kafka:
    build:
      context: src/main/docker/kafka
      dockerfile: src/main/docker/kafka/Dockerfile.jvm
    image: me.pcasaes/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: hexoids-kafka
      KAFKA_ZOOKEEPER_CONNECT: hexoids-zookeeper:2181
      KAFKA_OPTS: -javaagent:/opt/kafka/bin/jmx_prometheus_javaagent.jar=9080:/opt/kafka/bin/prometheus-config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - hexoids-zookeeper
    networks:
      - service-network

  hexoids-kafka-topic-create:
    build:
      context: src/main/docker/topics/
      dockerfile: Dockerfile
    image: me.pcasaes/hexoids-topics
    environment:
      BROKERS_LIST: hexoids-kafka:9092
    depends_on:
      - hexoids-kafka
    networks:
      - service-network

  hexoids:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/hexoids
    environment:
      - JAVA_EXTRA_OPTS=${JAVA_EXTRA_OPTS}
    depends_on:
      - hexoids-kafka
      - hexoids-kafka-topic-create
    ports:
      - "28080:8080"
    networks:
      - service-network

  hexoids-prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - service-network

  hexoids-grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    volumes:
      - ./src/main/monitoring/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - service-network

networks:
  service-network:
    name: hexoids-network
