services:


  hexoids-nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - service-network

  hexoids:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/hexoids
    environment:
      - VIRTUAL_HOST=${HEXOIDS_HOST}
      - VIRTUAL_PORT=8080
      - JAVA_EXTRA_OPTS=${JAVA_EXTRA_OPTS}
      - QUARKUS_PROFILE=api
    networks:
      - service-network

  hexoids-subscriber:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/hexoids
    environment:
      - JAVA_EXTRA_OPTS=${JAVA_EXTRA_OPTS}
      - QUARKUS_PROFILE=subscriber
    networks:
      - service-network

  hexoids-prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - service-network

  hexoids-grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    volumes:
      - ./src/main/monitoring/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - service-network

networks:
  service-network:
    name: hexoids-network
