version: '3.5'
services:
  hexoids-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - service-network
  hexoids-kafka:
    image: 'wurstmeister/kafka:2.12-2.3.1'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: hexoids-kafka
      KAFKA_ZOOKEEPER_CONNECT: hexoids-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - hexoids-zookeeper
    networks:
      - service-network
  hexoids-kafka-manager:
    container_name: kafka-manager
    hostname: kafka-manager
    image: solsson/kafka-manager:latest
    restart: always
    environment:
      - ZK_HOSTS=hexoids-zookeeper:2181
    ports:
      - "9000:9000"
    depends_on:
      - hexoids-zookeeper
      - hexoids-kafka
    networks:
      - service-network
networks:
  service-network:
    name: hexoids-network