version: '3.5'
services:

  hexoids-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - service-network

  hexoids-kafka:
    image: 'wurstmeister/kafka:2.12-2.5.0'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: hexoids-kafka
      KAFKA_ZOOKEEPER_CONNECT: hexoids-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - hexoids-zookeeper
    networks:
      - service-network

  hexoids-nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/nginx.tmpl:/app/nginx.tmpl
      - ./docker/sockets:/app/sockets
    networks:
      - service-network

  hexoids:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/hexoids
    environment:
      - VIRTUAL_HOST=${HEXOIDS_HOST}
      - VIRTUAL_PORT=8080
      - VIRTUAL_DOMAIN_SOCKET=${VIRTUAL_DOMAIN_SOCKET}
      - JAVA_EXTRA_OPTS=${JAVA_EXTRA_OPTS} -Dhexoids.config.service.kafka.subscriber=false
    depends_on:
      - hexoids-kafka
    volumes:
      - ./docker/sockets:/deployments/sockets
    networks:
      - service-network

  hexoids-subscriber:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: me.pcasaes/hexoids
    environment:
      - JAVA_EXTRA_OPTS=${JAVA_EXTRA_OPTS} -Dhexoids.config.service.kafka.subscriber=true -Dhexoids.config.service.client-broadcast.enabled=false
    depends_on:
      - hexoids-kafka
    networks:
      - service-network

networks:
  service-network:
    name: hexoids-network