"%dev":
  hexoids:
    config:
      player:
        reset:
          position: rng

"%test":
  hexoids:
    config:
      player:
        reset:
          position: 0,0
        max:
          move: 1

"%prod":
  hexoids:
    config:
      player:
        expunge-since-last-spawn-timeout: 180000
        reset:
          position: rng
      service:
        kafka:
          topics:
            bolt-life-cycle:
              partitions: 1


hexoids:
  config:
    infrastructure:
      players-spatial-index: rtree2
    client:
      assets: WEBASM
    update-frequency-in-millis: 50
    min:
      move: 0.0001
    inertia:
      dampen-coefficient: -0.001
    player:
      name-length: 8
      expunge-since-last-spawn-timeout: 60000
      max:
        move: 0.75
        bolts: 12
        angle:
          divisor: 4
      destroyed:
        shockwave:
          distance: 0.0408
          impulse: 0.004
          duration:
            ms: 400
    blackhole:
      eventhorizon:
        radius: 0.005 # within this radius ships are destroyed
      gravity:
        radius: 0.07 # within this radius ships start to feel gravity's effect. The closer to the event horizon the higher the acceleration
        impulse: 0.07 # at every physics iteration this factor is applied to acceleration
      dampen:
        factor: 5 # used to reduce effect of the inertial dampener. Factor is applied to acceleration
      genesis:
        probability:
          factor: 3 # int: the higher, the more likely to appear. 0 disables. Probability = (factor-2)/factor
      teleport:
        probability: 0.05 # Chances of random teleportation when passing event horizon
    bolt:
      max:
        duration: 10000
      speed: 0.07
      inertia:
        enabled: true
        rejection-scale: 0.8
        projection-scale: 0.8
        negative-projection-max: 0.1
      collision:
        radius: 0.001

    service:
      disruptor:
        buffer-size-exponent: 17
      client-broadcast:
        enabled: true
        batch:
          size: 64
          timeout: 20
      kafka:
        subscriber: true
        topics:
          bolt-life-cycle:
            partitions: 1

mp:
  messaging:
    outgoing:
      join-game-out:
        connector: smallrye-kafka
        topic: JOIN_GAME_TOPIC
        value:
          serializer: me.pcasaes.hexoids.infrastructure.kafka.converter.EventDtoSerializer
        key:
          serializer: me.pcasaes.hexoids.infrastructure.kafka.converter.UUIDBytesSerializer
        acks: 0
        retries: 0
        linger:
          ms: 50
        waitForWriteCompletion: false

      score-board-control-out:
        connector: smallrye-kafka
        topic: SCORE_BOARD_CONTROL_TOPIC
        value:
          serializer: me.pcasaes.hexoids.infrastructure.kafka.converter.EventDtoSerializer
        key:
          serializer: me.pcasaes.hexoids.infrastructure.kafka.converter.UUIDBytesSerializer
        acks: 0
        retries: 0
        linger:
          ms: 100
        waitForWriteCompletion: false

      score-board-update-out:
        connector: smallrye-kafka
        topic: SCORE_BOARD_UPDATE_TOPIC
        value:
          serializer: me.pcasaes.hexoids.infrastructure.kafka.converter.EventDtoSerializer
        key:
          serializer: me.pcasaes.hexoids.infrastructure.kafka.converter.UUIDBytesSerializer
        acks: 0
        retries: 0
        linger:
          ms: 100
        waitForWriteCompletion: false

    incoming:
      join-game:
        connector: smallrye-kafka
        topic: JOIN_GAME_TOPIC
        pause-if-no-requests: false
        value:
          deserializer: me.pcasaes.hexoids.infrastructure.kafka.converter.EventDtoDeserializer
        key:
          deserializer: me.pcasaes.hexoids.infrastructure.kafka.converter.UUIDBytesDeserializer
        consumer-rebalance-listener:
          name: CatchupRebalanceListener
        enable:
          auto:
            commit: false
        commit-strategy: ignore
        auto:
          offset:
            reset: earliest
        group:
          instance:
            id: static-join-game
        session:
          timeout:
            ms: 60000


      score-board-control:
        connector: smallrye-kafka
        topic: SCORE_BOARD_CONTROL_TOPIC
        pause-if-no-requests: false
        value:
          deserializer: me.pcasaes.hexoids.infrastructure.kafka.converter.EventDtoDeserializer
        key:
          deserializer: me.pcasaes.hexoids.infrastructure.kafka.converter.UUIDBytesDeserializer
        consumer-rebalance-listener:
          name: DelayedStartConsumerRebalanceListener
        enable:
          auto:
            commit: false
        commit-strategy: throttled
        auto:
          commit:
            interval:
              ms: 10000
          offset:
            reset: latest
        group:
          id: hexoids-server-score-board-control

      score-board-update:
        connector: smallrye-kafka
        topic: SCORE_BOARD_UPDATE_TOPIC
        pause-if-no-requests: false
        value:
          deserializer: me.pcasaes.hexoids.infrastructure.kafka.converter.EventDtoDeserializer
        key:
          deserializer: me.pcasaes.hexoids.infrastructure.kafka.converter.UUIDBytesDeserializer
        consumer-rebalance-listener:
          name: DelayedStartConsumerRebalanceListener
        enable:
          auto:
            commit: false
        commit-strategy: ignore
        auto:
          offset:
            reset: earliest
        group:
          instance:
            id: static-score-board-update
        session:
          timeout:
            ms: 60000

kafka:
  bootstrap:
    servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}

quarkus:
  vertx:
    prefer-native-transport: true
    cluster:
      clustered: true
  http:
    so-reuse-port: true
    tcp-quick-ack: true
    tcp-cork: false
    tcp-fast-open: true
  log:
    category:
      "io.quarkus.vertx.core.runtime.VertxCoreRecorder":
        level: DEBUG
  micrometer:
    binder:
      vertx:
        enabled: false
