"%dev":
  hexoids:
    config:
      player:
        reset:
          position: rng

"%test":
  hexoids:
    config:
      player:
        reset:
          position: 0,0
        max:
          move: 1

"%prod":
  hexoids:
    config:
      player:
        expunge-since-last-spawn-timeout: 180000
        reset:
          position: rng
      service:
        kafka:
          topics:
            bolt-life-cycle:
              partitions: 1


hexoids:
  config:
    update-frequency-in-millis: 50
    min:
      move: 0.0001
    inertia:
      dampen-coefficient: -0.001
    player:
      name-length: 7
      expunge-since-last-spawn-timeout: 60000
      max:
        move: 0.2
        bolts: 12
        angle:
          divisor: 4
    bolt:
      max:
        duration: 10000
      speed: 0.07
      inertia:
        enabled: true
        rejection-scale: 0.8
        projection-scale: 0.8
        negative-projection-max: 0.1
      collision:
        radius: 0.001

    service:
      disruptor:
        buffer-size-exponent: 17
      client-broadcast:
        enabled: true
        batch:
          size: 64
          timeout: 20
      kafka:
        subscriber: true
        topics:
          bolt-life-cycle:
            partitions: 1

mp:
  messaging:
    outgoing:
      join-game-out:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: JOIN_GAME_TOPIC
        value:
          serializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoSerializer
        key:
          serializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesSerializer
        acks: 0
        waitForWriteCompletion: false

      player-action-out:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: PLAYER_ACTION_TOPIC
        value:
          serializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoSerializer
        key:
          serializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesSerializer
        acks: 0
        waitForWriteCompletion: false

      bolt-life-cycle-out:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: BOLT_LIFECYCLE_TOPIC
        value:
          serializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoSerializer
        key:
          serializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesSerializer
        acks: 0
        waitForWriteCompletion: false

      bolt-action-out:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: BOLT_ACTION_TOPIC
        value:
          serializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoSerializer
        key:
          serializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesSerializer
        acks: 0
        waitForWriteCompletion: false

      score-board-control-out:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: SCORE_BOARD_CONTROL_TOPIC
        value:
          serializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoSerializer
        key:
          serializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesSerializer
        acks: 0
        waitForWriteCompletion: false

      score-board-update-out:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: SCORE_BOARD_UPDATE_TOPIC
        value:
          serializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoSerializer
        key:
          serializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesSerializer
        acks: 0
        waitForWriteCompletion: false

    incoming:
      join-game:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: JOIN_GAME_TOPIC
        value:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoDeserializer
        key:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesDeserializer
        enable:
          auto:
            commit: false
        auto:
          offset:
            reset: earliest
        group:
          instance:
            id: static
        session:
          timeout:
            ms: 60000

      player-action:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: PLAYER_ACTION_TOPIC
        value:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoDeserializer
        key:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesDeserializer
        enable:
          auto:
            commit: false
        auto:
          offset:
            reset: earliest
        group:
          instance:
            id: static
        session:
          timeout:
            ms: 60000

      bolt-life-cycle:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: BOLT_LIFECYCLE_TOPIC
        value:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoDeserializer
        key:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesDeserializer
        enable:
          auto:
            commit: false
        auto:
          offset:
            reset: earliest
        group:
          id: hexoids-server-bolt-life-cycle

      bolt-action:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: BOLT_ACTION_TOPIC
        value:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoDeserializer
        key:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesDeserializer
        enable:
          auto:
            commit: false
        auto:
          offset:
            reset: earliest
        group:
          instance:
            id: static
        session:
          timeout:
            ms: 60000

      score-board-control:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: SCORE_BOARD_CONTROL_TOPIC
        value:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoDeserializer
        key:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesDeserializer
        enable:
          auto:
            commit: true
        auto:
          commit:
            interval:
              ms: 10000
          offset:
            reset: latest
        group:
          id: hexoids-server-score-board-control

      score-board-update:
        connector: smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BROKER_LIST:hexoids-kafka:9092}
        topic: SCORE_BOARD_UPDATE_TOPIC
        value:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.EventDtoDeserializer
        key:
          deserializer: me.pcasaes.hexoids.service.kafka.converter.UUIDBytesDeserializer
        enable:
          auto:
            commit: false
        auto:
          offset:
            reset: earliest
        group:
          instance:
            id: static
        session:
          timeout:
            ms: 60000


quarkus:
  vertx:
    prefer-native-transport: true
  http:
    so-reuse-port: true
    tcp-quick-ack: true
    tcp-cork: false
    tcp-fast-open: true
  log:
    category:
      "io.quarkus.vertx.core.runtime.VertxCoreRecorder":
        level: DEBUG