"%dev":
  hexoids:
    config:
      player:
        reset:
          position: rng

"%test":
  hexoids:
    config:
      player:
        reset:
          position: 0,0
        max:
          move: 1

"%prod":
  hexoids:
    config:
      player:
        expunge-since-last-spawn-timeout: 180000
        reset:
          position: rng
      service:
        kafka:
          topics:
            bolt-life-cycle:
              partitions: 1


hexoids:
  config:
    update-frequency-in-millis: 50
    min:
      move: 0.0001
    inertia:
      dampen-coefficient: -0.001
    player:
      name-length: 7
      expunge-since-last-spawn-timeout: 60000
      max:
        move: 10
        bolts: 10
        angle:
          divisor: 4
    bolt:
      max:
        duration: 10000
      speed: 0.07
      inertia:
        enabled: true
        rejection-scale: 0.8
        projection-scale: 0.8
        negative-projection-max: 0.1
      collision:
        radius: 0.001

    service:
      client-broadcast:
        enabled: true
        batch:
          size: 64
          timeout: 20
        event-queue:
          linked-list: false
          exponent: 17
          sleep-on-empty: 5
      domain-event:
        event-queue:
          linked-list: false
          exponent: 17
          sleep-on-empty: 5
      game-loop:
        event-queue:
          linked-list: false
          exponent: 17
      kafka:
        subscriber: true
        topics:
          bolt-life-cycle:
            partitions: 1
