"%dev":
  bbop:
    config:
      player:
        reset:
          position: rng

"%test":
  bbop:
    config:
      player:
        reset:
          position: 0,0
        max:
          move: 1

"%prod":
  bbop:
    config:
      player:
        expungeSinceLastSpawnTimeout: 180000
        reset:
          position: rng
      service:
        kafka:
          topics:
            bolt_life_cycle:
              partitions: 1


bbop:
  config:
    min:
      move: 0.000000001
    player:
      expungeSinceLastSpawnTimeout: 60000
      max:
        move: 10
        bolts: 10
        angle:
          divisor: 4
    bolt:
      max:
        duration: 10000
      speed: 0.07
      collision:
        radius: 0.001

    service:
      client:
        broadcast:
          enabled: true
          batch:
            size: 64
            timeout: 20
          eventqueue:
            linkedlist: false
            exponent: 17
      domain:
        event:
          eventqueue:
            linkedlist: false
            exponent: 17
      game:
        loop:
          eventqueue:
            linkedlist: false
            exponent: 17
      kafka:
        subscriber: true
        topics:
          bolt_life_cycle:
            partitions: 1
