global:
  scrape_interval:     15s

  external_labels:
    monitor: 'hexoids-monitor'

scrape_configs:
  - job_name: 'hexoids'
    scrape_interval: 2s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['hexoids_hexoids_1:8080', 'hexoids_hexoids_2:8080', 'hexoids_hexoids_3:8080']
        labels:
          service: 'web-entrypoint'
      - targets: ['hexoids_hexoids-subscriber_1:8080', 'hexoids_hexoids-subscriber_2:8080', 'hexoids_hexoids-subscriber_3:8080']
        labels:
          service: 'consumer-entrypoint'


  - job_name: 'kafka-server'
    scrape_interval: 2s
    static_configs:
      - targets: ['hexoids-kafka:9080']
