global:
  scrape_interval:     15s

  external_labels:
    monitor: 'hexoids-monitor'

scrape_configs:
  - job_name: 'hexoids'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['hexoids:8080']